<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ClassicMac.Resources.Decoders\ClassicMac.Resources.Decoders.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\Shared\CorpusFolders.cs" Link="Shared\CorpusFolders.cs" />
    <Compile Include="..\ClassicMac.Graphics.Tests\Fonts\FontBuilder.cs" Link="Builders\FontBuilder.cs" />
    <Compile Include="..\ClassicMac.Code.Tests\PefBuilder.cs" Link="Builders\PefBuilder.cs" />
    <Compile Include="..\ClassicMac.Code.Tests\CodeCorpus.cs" Link="Shared\CodeCorpus.cs" />
  </ItemGroup>
</Project>
