<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Avalonia.Headless" />
    <PackageReference Include="Avalonia.Skia" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\ClassicMac.Files.Tests\HfsBuilder.cs" Link="Builders\HfsBuilder.cs" />
    <Compile Include="..\ClassicMac.Files.Tests\NdifBuilder.cs" Link="Builders\NdifBuilder.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ClassicMac.App\ClassicMac.App.csproj" />
  </ItemGroup>

</Project>
