using System.Runtime.CompilerServices;
using TrapTables;

namespace ClassicMac.Code.Tests.Disassembly;

// Runs tools/TrapTables on the hand-written defs in TrapTablesFixture and checks the C# it writes.
public sealed class TrapTablesGeneratorTests : IDisposable
{
    private readonly string _out = Path.Combine(Path.GetTempPath(), "TrapTablesTest-" + Guid.NewGuid().ToString("N"));
    private readonly string _traps, _selectors, _lowmem;

    public TrapTablesGeneratorTests()
    {
        TrapTablesGenerator.Generate(Fixture("TrapTablesFixture"), _out);
        _traps = File.ReadAllText(Path.Combine(_out, "TrapNames.g.cs"));
        _selectors = File.ReadAllText(Path.Combine(_out, "SelectorNames.g.cs"));
        _lowmem = File.ReadAllText(Path.Combine(_out, "LowMemoryGlobals.g.cs"));
    }

    public void Dispose() => Directory.Delete(_out, recursive: true);

    private static string Fixture(string name, [CallerFilePath] string here = "") =>
        Path.Combine(Path.GetDirectoryName(here)!, name);

    [Fact]
    public void Header()
    {
        foreach (string text in new[] { _traps, _selectors, _lowmem })
        {
            Assert.StartsWith("// <auto-generated>\n", text);
            Assert.Contains("Multiversal Interfaces (https://github.com/autc04/multiversal, MIT,", text);
            Assert.Contains("\nnamespace ClassicMac.Code.Disassembly;\n\npublic static partial class ", text);
            Assert.DoesNotContain("\r", text);
        }
    }

    [Theory]
    [InlineData("(0xA11E, \"NewPtr\", TrapModifierKind.Memory),")]       // MemoryMgr.yaml: Memory Manager bits
    [InlineData("(0xA0F0, \"PBFileCall\", TrapModifierKind.File),")]     // file_trap: File Manager bits
    [InlineData("(0xA3AD, \"NewGestalt\", TrapModifierKind.None),")]     // TrapBits dispatcher: $A1AD | $200
    [InlineData("(0xA9EE, \"Pack7\", TrapModifierKind.None),")]          // a dispatcher is a trap too
    [InlineData("(0xA822, \"ResourceDispatch\", TrapModifierKind.None),")]
    [InlineData("(0xA9F0, \"LoadSeg\", TrapModifierKind.None),")]        // supplements
    [InlineData("(0xA1AD, \"Gestalt\", TrapModifierKind.None),")]        // supplement renames GestaltDispatch
    [InlineData("(0xA000, \"Open\", TrapModifierKind.File),")]           // supplement with no Multiversal entry
    [InlineData("(0xA004, \"Control\", TrapModifierKind.Device),")]
    [InlineData("(0xA03C, \"CmpString\", TrapModifierKind.String),")]
    [InlineData("(0xAAFE, \"MixedModeMagic\", TrapModifierKind.None),")]
    public void TrapEntries(string line) => Assert.Contains(line, _traps);

    [Theory]
    [InlineData("SecondDefinition")]   // a later definition of the same word loses
    [InlineData("CarbonOnly")]         // - api: carbon items are skipped
    [InlineData("ROMlib_Hidden")]      // Executor's internal entry points
    [InlineData("GestaltDispatch")]
    public void TrapsLeftOut(string name) => Assert.DoesNotContain("\"" + name + "\"", _traps);

    [Fact]
    public void TrapsSorted()
    {
        var words = System.Text.RegularExpressions.Regex.Matches(_traps, @"\(0x([0-9A-F]{4}), """)
            .Select(m => Convert.ToUInt16(m.Groups[1].Value, 16)).ToList();
        Assert.Equal(words.Order(), words);
        Assert.Equal(words.Distinct().Count(), words.Count);
    }

    [Theory]
    [InlineData("(0xA9EE, \"Pack7\", SelectorLocation.Stack, SelectorWidth.Word, 0xFFFF),")]
    [InlineData("(0xA8B5, \"ScriptUtil\", SelectorLocation.Stack, SelectorWidth.Long, 0xFFFFFFFF),")]
    [InlineData("(0xA822, \"ResourceDispatch\", SelectorLocation.D0, SelectorWidth.Word, 0xF),")]
    [InlineData("(0xA1AD, \"Gestalt\", SelectorLocation.D0, SelectorWidth.OSType, 0xFFFFFFFF),")]
    [InlineData("(0xA260, \"HFSDispatch\", SelectorLocation.D0, SelectorWidth.Word, 0xFFFF),")] // supplement
    [InlineData("(0xA9EE, 0x0, \"NumToString\"),")]
    [InlineData("(0xA9EE, 0x1, \"StringToNum\"),")]                     // a decimal selector
    [InlineData("(0xA8B5, 0x8008FFF2, \"LongDateToSeconds\"),")]
    [InlineData("(0xA1AD, 0x73797376, \"gestaltSystemVersion\"),")]     // 'sysv'
    public void SelectorEntries(string line) => Assert.Contains(line, _selectors);

    [Theory]
    [InlineData("ROMlib_Hidden")]
    [InlineData("FinaleUnknown1")]      // Executor's placeholder names
    [InlineData("notAGestaltName")]
    [InlineData("gestaltNumber")]       // not an OSType
    [InlineData("NotThis")]             // inside a block scalar
    public void SelectorsLeftOut(string name) => Assert.DoesNotContain(name, _selectors);

    [Theory]
    [InlineData("(0x0904, \"CurrentA5\", 4, \"Ptr\"),")]
    [InlineData("(0x0A00, \"Pats\", 8, \"Byte[8]\"),")]
    [InlineData("(0x014A, \"EventQueue\", 10, \"QHdr\"),")]
    public void LowMemoryEntries(string line) => Assert.Contains(line, _lowmem);

    [Fact]
    public void LowMemoryLeftOut()
    {
        Assert.DoesNotContain("executorlabel", _lowmem);   // Executor's lower-case labels
        Assert.DoesNotContain("0x0999", _lowmem);          // inside a block scalar
        Assert.True(_lowmem.IndexOf("0x014A", StringComparison.Ordinal) < _lowmem.IndexOf("0x0904", StringComparison.Ordinal));
    }

    [Fact]
    public void UnknownLowMemoryTypeFails()
    {
        string dir = Path.Combine(_out, "bad");
        Assert.Throws<InvalidDataException>(() => TrapTablesGenerator.Generate(Fixture("TrapTablesBadFixture"), dir));
    }
}
