using System.Globalization;
using System.Text;

// Writes ClassicMac.Core's MacEncodingCorrections.g.cs: for each Mac encoding, the codes where Apple's mapping table
// (unicode.org VENDORS/APPLE, Apple's licence; never committed) maps differently from .NET's code page, as code and
// Unicode only (docs/formats/codecs/text-encodings.md §5).
// Usage: dotnet run --project tools/EncodingTables [tables folder] [output file]
// The folder defaults to tests/golden/encodings and the output to src/ClassicMac.Core/MacEncodingCorrections.g.cs. The
// output is checked in; rerun this tool only when the tables or .NET's code pages change.
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
string folder = args.Length > 0 ? args[0] : Path.Combine("tests", "golden", "encodings");
string output = args.Length > 1 ? args[1] : Path.Combine("src", "ClassicMac.Core", "MacEncodingCorrections.g.cs");

(string Name, string File, int CodePage)[] encodings =
[
    ("Japanese", "JAPANESE.TXT", 10001), ("ChineseTraditional", "CHINTRAD.TXT", 10002), ("Korean", "KOREAN.TXT", 10003),
    ("Arabic", "ARABIC.TXT", 10004), ("Hebrew", "HEBREW.TXT", 10005), ("Greek", "GREEK.TXT", 10006),
    ("Cyrillic", "CYRILLIC.TXT", 10007), ("ChineseSimplified", "CHINSIMP.TXT", 10008), ("Romanian", "ROMANIAN.TXT", 10010),
    ("Ukrainian", "UKRAINE.TXT", 10017), ("Thai", "THAI.TXT", 10021), ("CentralEuropean", "CENTEURO.TXT", 10029),
    ("Icelandic", "ICELAND.TXT", 10079), ("Turkish", "TURKISH.TXT", 10081), ("Croatian", "CROATIAN.TXT", 10082),
];

var code = new StringBuilder();
code.AppendLine("// <auto-generated>");
code.AppendLine("// Generated by tools/EncodingTables from Apple's Mac OS mapping tables; do not edit.");
code.AppendLine("// </auto-generated>");
code.AppendLine("using System.Collections.Generic;");
code.AppendLine();
code.AppendLine("namespace ClassicMac.Core;");
code.AppendLine();
code.AppendLine("/// <summary>Where Apple's mapping tables differ from .NET's Mac code pages: each code (one byte, or lead &lt;&lt; 8 | trail) and Apple's Unicode.</summary>");
code.AppendLine("internal static class MacEncodingCorrections");
code.AppendLine("{");
code.AppendLine("    public static readonly Dictionary<MacTextEncoding, (int Code, string Text)[]> All = new()");
code.AppendLine("    {");
int total = 0;
foreach (var (name, file, codePage) in encodings)
{
    var path = Path.Combine(folder, file);
    if (!File.Exists(path))
    {
        Console.Error.WriteLine($"{path} is missing.");
        return 1;
    }

    var net = Encoding.GetEncoding(codePage, EncoderFallback.ReplacementFallback, DecoderFallback.ReplacementFallback);
    var corrections = new List<(int Code, string Text)>();
    foreach (var line in File.ReadLines(path))
    {
        var fields = line.Split('#')[0].Split('\t', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        if (fields.Length < 2 || !fields[0].StartsWith("0x", StringComparison.Ordinal))
        {
            continue;
        }

        var bytes = Convert.FromHexString(fields[0][2..]);
        var apple = string.Concat(fields[1].Split('+').Where(f => f.StartsWith("0x", StringComparison.Ordinal))
            .Select(f => char.ConvertFromUtf32(int.Parse(f[2..], NumberStyles.HexNumber, CultureInfo.InvariantCulture))));
        if (net.GetString(bytes) != apple)
        {
            corrections.Add((bytes.Length == 1 ? bytes[0] : bytes[0] << 8 | bytes[1], apple));
        }
    }

    code.AppendLine(CultureInfo.InvariantCulture, $"        [MacTextEncoding.{name}] =");
    code.AppendLine("        [");
    foreach (var (c, text) in corrections)
    {
        var escaped = string.Concat(text.Select(ch => $"\\u{(int)ch:X4}"));
        code.AppendLine(CultureInfo.InvariantCulture, $"            (0x{c:X}, \"{escaped}\"),");
    }

    code.AppendLine("        ],");
    total += corrections.Count;
    Console.WriteLine($"{name}: {corrections.Count} corrections");
}

code.AppendLine("    };");
code.AppendLine("}");
File.WriteAllText(output, code.ToString().Replace("\r\n", "\n", StringComparison.Ordinal));
Console.WriteLine($"{total} corrections to {output}");
return 0;
